export enum ActionTypes {
  SET_OFFERS = 'SET_OFFERS',
  SET_OFFER = 'SET_OFFER',
  SET_USER_OFFERS = 'SET_USER_OFFERS',
  SET_OFFER_PAGINATION_PROPS = 'SET_OFFER_PAGINATION_PROPS',
  SET_CATEGORIES = 'SET_CATEGORIES',
  SET_CATEGORY = 'SET_CATEGORY',
  SET_OFFER_LOADING = 'SET_OFFER_LOADING',
  SET_CATEGORY_LOADING = 'SET_CATEGORY_LOADING',
  SET_USER_LOADING = 'SET_USER_LOADING',
  SET_USER = 'SET_USER',
  SET_USERS = 'SET_USERS'
}
